# Docker Compose configuration file defining a multi-service application:
# - volumes: Defines persistent storage for postgres and general storage
# - db: PostgreSQL database service running on Alpine Linux
# - redis: Redis cache service running on Alpine Linux 
# - nginx: Nginx web server that proxies requests to frontend/backend
# - frontend: Vue.js application built from base-vue image
# - backend: Python application built from base-python image
# - background: Celery worker for background task processing

volumes:
  postgres_data:
  storage_data:

services:
  db:
    image: "postgres:alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  nginx:
    image: "nginx:alpine"
    restart: always
    depends_on:
      - frontend
      - backend
    volumes:
      - ./compose/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"

  frontend:
    image: base-vue:latest
    build:
      dockerfile: ./compose/Dockerfile
      context: .
      target: base-vue
    volumes:
      - ./vue/:/app/
      - /app/node_modules/
    command: npm run dev

  backend:
    image: base-python:latest
    build:
      dockerfile: ./compose/Dockerfile
      context: .
      target: base-python
    volumes:
      - ./:/app/
    environment:
      - DB_HOST=db
    command: python3 manage.py runserver 0.0.0.0:8000

  background:
    image: base-python:latest
    volumes:
      - ./:/app/
    command: celery -A config worker -l INFO
